### ISSUE TITLE
hosting-related issue

### ISSUE THREAD

**Issue by Mohamed01555** [Ruu3f/freeGPT#11]
I built an app depends on your `gpt4.py` script and it works properly locally, however, when I hosted my app on streamlit and Huggingface spaces both of them replied with the `Exception ("Unable to fetch response.")` . Note that both servers accept `gpt3.py` script and fetch the answer using it without problems. I asked ChatGPT and gave him the code of both scripts and he replied that the issue may be with the `tls_client` library
what is the reason of this ? and how can i solve it?

**Comment by Ruu3f** [comment]
The same thing happens to me as well. It's likely that there's an issue with tls_client. My only option is to use something other than tls_client; I'll be doing that soon.

**Comment by Mohamed01555** [comment]
Do you think that both streamlit and hugging face restricted their servers not to scrap data from websites ? I think so because if the issue is in tls_client ,it will not work locally, but since it worked then the issue is in their servers What is your opinion?

**Comment by Mohamed01555** [comment]
Also when I converted my web app to executable file also it didn't fetch the response , I am astonishing regarding this? Any contribution will be appreciated.

**Comment by Mohamed01555** [comment]
The last one,  why did you use tls_client not requests or aiohttp like in your gpt3 script?
