### ISSUE TITLE
why tls_cilent

### ISSUE THREAD

**Issue by Mohamed01555** [Ruu3f/freeGPT#13]
Do you think that both streamlit and hugging face restricted their servers not to scrap data from websites ? I think so because if the issue is in tls_client ,it will not work locally, but since it worked then the issue is in their servers What is your opinion?

Also when I converted my web app to executable file also it didn't fetch the response , I am astonishing regarding this? Any contribution will be appreciated.

The last one, why did you use tls_client not requests or aiohttp like in your gpt3 script?

**Comment by Ruu3f** [comment]
Finally, I replaced `tls-client` with something else, `curl-cffi` in this case.
