### ISSUE TITLE
Failed to perform, ErrCode: 77

### ISSUE THREAD

**Issue by UserJoo9** [Ruu3f/freeGPT#16]
**Describe the bug**
when i converted 'py' file to .exe i faced this issue
(Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\JooDe\AppData\Local\Temp\_MEI99322\curl_cffi\cacert.pem CApath: none')
i don't know why its brings, when its already working in 'py' file without errors.

 - OS: Windows 10 64bit
 - Python Version: 3.11.2

![Screenshot 2023-09-03 005929](https://github.com/Ruu3f/freeGPT/assets/82382970/10ba7c3d-c73f-4d51-a543-d69be31dc4f2)

**Comment by Ruu3f** [comment]
I will fix it soon and try again to use aiohttp.

**Comment by UserJoo9** [comment]
please can you tell me how yo use aiohttp with your FreeGPT briefly..?
