### ISSUE TITLE
gpt4.py script does no longer work

### ISSUE THREAD

**Issue by Mohamed01555** [Ruu3f/freeGPT#17]
gpt4.py script does no longer work , It replies with "Unable to fetch response."

**Comment by Ruu3f** [comment]
What version are you on?

**Comment by Mohamed01555** [comment]
I used both tls_client and curl_ciffi 
Please use it now and check if it is still working

**Comment by Mohamed01555** [comment]
now it works alhamdullah, it stopped working for me for some time

**Comment by Ruu3f** [comment]
Oh, Alright. I'm closing this issue. Feel free to open a new one if you need further assistance.
