### ISSUE TITLE
bots does not have memory

### ISSUE THREAD

**Issue by Mohamed01555** [Ruu3f/freeGPT#18]
why do gpt3 or gpt4 bots not have memory? Although they have memory on their websites whether `you.com` or `AIChatOS `.
Appreciate your response

**Comment by Ruu3f** [comment]
There are many reasons for that. But you can easily do that, here is an example:
```py
import freeGPT
from asyncio import run


async def main():
    chat_history = []
    while True:
        prompt = input("👦: ")
        try:
            resp = (
                await getattr(freeGPT, "gpt3")
                .Completion()
                .create(f"Chat history: {chat_history}. Prompt: {prompt}")
            )
            print(f"🤖: {resp}")
            chat_history.append(f"Prompt: {prompt}. Your Response: {resp}")
        except Exception as e:
            print(f"🤖: {e}")


run(main())
```

**Comment by Mohamed01555** [comment]
please give a few of them, please

**Comment by Ruu3f** [comment]
?

**Comment by Ruu3f** [comment]
- I want all of the models' usage to be same. Since only 2 of the providers provide chat history, I cannot do that.
- You can easily add it in your code. (using the example I gave)
