### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by janiosarmento** [Ruu3f/freeGPT#22]
I'm trying to install this on a Raspberry Pi, but it won't run because of:

`ModuleNotFoundError: No module named 'curl_cffi'`

What about adding a `requirements.txt` to the repo?

Thanks!

**Comment by Ruu3f** [comment]
I don't know much about Raspberry Pi, but it should install these before installing the package itself:
![image](https://github.com/Ruu3f/freeGPT/assets/78753690/3fcd816b-1281-4a0d-90f4-d19655007ae7)

**Comment by janiosarmento** [comment]
I made it run by manually installing the packages.

**Comment by Ruu3f** [comment]
👍
