### ISSUE TITLE
Can't use falcon_40b or alpaca_7b

### ISSUE THREAD

**Issue by FinleyKurtz16** [Ruu3f/freeGPT#24]
**Describe the bug**
If you try to use falcon_40b or alpaca_7b, whether in synchro or in ansychromode it doesn't work. The Error I get is 'conversationID'

**To Reproduce**
Paste this code:
from freeGPT import AsyncClient
from asyncio import run

async def main():
    while True:
        prompt = input("👦: ")
        try:
            resp = await AsyncClient.create_completion("falcon_40b", prompt)
            print(f"🤖: {resp}")
        except Exception as e:
            print(f"🤖: {e}")

run(main())

or paste this code:

from freeGPT import Client

while True:
    prompt = input("👦: ")
    try:
        resp = Client.create_completion("falcon_40b", prompt)
        print(f"🤖: {resp}")
    except Exception as e:
        print(f"🤖: {e}")

**Expected behavior**

**Desktop:**
 - OS: Windows 11 (doesn't work on Google Collab either)

**Additional context**
I tried many things to fix this "bug", but I can't find the solution for this problem, except using gpt3 or gpt4, but for my Ai-project its very important to use falcon_40b.

**Comment by Ruu3f** [comment]
Those weren't working, I've removed them and uploaded a new version.

**Comment by FinleyKurtz16** [comment]
But is there a way to add an AI that is unfiltered. But AI's like falcon_40b. And is there a way to make the Ai german, because in your source_code there is a variable called: talk always english.

**Comment by Ruu3f** [comment]
You can change the prompt to whatever you want, if you want it to talk in German, simply make a prompt for it. You can do it like this: (3_5)

```py
"messages": [
    {"role": "system", "content": "Always talk in German and unfiltered."},
    {"role": "user", "content": prompt}
],
```

Replace the original line with this.

**Comment by FinleyKurtz16** [comment]
> You can change the prompt to whatever you want, if you want it to talk in German, simply make a prompt for it. You can do it like this: (3_5)
> 
> ```python
> "messages": [
>     {"role": "system", "content": "Always talk in German and unfiltered."},
>     {"role": "user", "content": prompt}
> ],
> ```
> 
> Replace the original line with this.

I mean, you.com and the other providers surely have a filter that cannot be disabled. For example, if you ask whether the AI can insult you, the filter will always kick in. And if I need to change something in the code you mentioned, I have to download the source code and integrate it locally, not through the console, right?

**Comment by Ruu3f** [comment]
Well, you.com does, and from (3_5) I meant [this](https://github.com/Ruu3f/freeGPT/blob/main/freeGPT/Client/gpt3_5.py), which doesn't have the filter.
