### ISSUE TITLE
Both gpt3 and gpt4 does not work!

### ISSUE THREAD

**Issue by Shreyas-ITB** [Ruu3f/freeGPT#3]
Trying the code in the readme file for gpt3 throws session not found error. while trying gpt4 throws a bunch of json data and just crashes.

**Comment by Ruu3f** [comment]
Hey, could you please send me those errors you are getting?

**Comment by Ruu3f** [comment]
> Trying the code in the readme file for gpt3 throws session not found error. while trying gpt4 throws a bunch of json data and just crashes.

Hey, could you please send me those errors you are getting?

**Comment by Shreyas-ITB** [comment]
> > Trying the code in the readme file for gpt3 throws session not found error. while trying gpt4 throws a bunch of json data and just crashes.
> 
> Hey, could you please send me those errors you are getting?

Hi! I managed to solve the gpt3 issue by just re running the code. But gpt4 issue still persists. 
`sua_2Qy0Wp6gGXuqzgb5MJlfG0yu5MU
{"response":{"object":"sign_up_attempt","id":"sua_2Qy0Wp6gGXuqzgb5MJlfG0yu5MU","status":"missing_requirements","required_fields":["email_address"],"optional_fields":["password","oauth_google","phone_number","first_name","last_name"],"missing_fields":[],"unverified_fields":["email_address"],"verifications":{"email_address":{"status":"unverified","strategy":"email_link","attempts":null,"expire_at":1686311148366,"next_action":"needs_attempt","supported_strategies":["email_link"]},"phone_number":null,"web3_wallet":null,"external_account":null},"username":null,"email_address":"grizzleddingo2@internetkeno.com","phone_number":null,"web3_wallet":null,"password_enabled":false,"first_name":null,"last_name":null,"unsafe_metadata":{},"public_metadata":{},"custom_action":false,"external_id":null,"created_session_id":null,"created_user_id":null,"abandon_at":1686396947833},"client":{"object":"client","id":"client_2Qy0Wk0COTVPDXNm79pYNoefyec","sessions":[],"sign_in":null,"sign_up":{"object":"sign_up_attempt","id":"sua_2Qy0Wp6gGXuqzgb5MJlfG0yu5MU","status":"missing_requirements","required_fields":["email_address"],"optional_fields":["password","oauth_google","phone_number","first_name","last_name"],"missing_fields":[],"unverified_fields":["email_address"],"verifications":{"email_address":{"status":"unverified","strategy":"email_link","attempts":null,"expire_at":1686311148366,"next_action":"needs_attempt","supported_strategies":["email_link"]},"phone_number":null,"web3_wallet":null,"external_account":null},"username":null,"email_address":"grizzleddingo2@internetkeno.com","phone_number":null,"web3_wallet":null,"password_enabled":false,"first_name":null,"last_name":null,"unsafe_metadata":{},"public_metadata":{},"custom_action":false,"external_id":null,"created_session_id":null,"created_user_id":null,"abandon_at":1686396947833},"last_active_session_id":null,"created_at":1686310547830,"updated_at":1686310547837}}
64830e97985cd29ca098244e
https://clerk.forefront.ai/v1/verify?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODYzMTExNDgsImlpZCI6Imluc18yTzZ3UTFYd3dxVFdXUWUyQ1VYZHZ2bnNaY2UiLCJydXJsIjoiaHR0cHM6Ly9hY2NvdW50cy5mb3JlZnJvbnQuYWkvc2lnbi11cC92ZXJpZnkiLCJzaWQiOiJzdWFfMlF5MFdwNmdHWHVxemdiNU1KbGZHMHl1NU1VIiwic3QiOiJzaWduX3VwX2F0dGVtcHQiLCJ2aWQiOiJ2ZXJfMlF5MFd4ZnliU3V4eXhkQzZqM05reDVKOEJZIn0.VLnMva7TV7LeUaFjhg0BcmL_S2WkGDQJjw2UUFxw61nVJArhF3bIs3NrmN3Xxuq8iWglupM0Lj3tuPFEbUuDTVbPa-T-j8KkoWuFUhhx92VcpGtAlyEf5vwI60aP1R7o4q7bJbT21eSMfQji7Bdz7xsrCSGqERsEX_L6Od4fhqC-rSol2w1pqUflGZcUeg3SalYZ-x27zMXaslfO5TiSTw6VTMT_Mp2-u4hKz-N1F9nUchE1tCCa2MQJAmsAV8g3L6-x9nxdvmEfDfjVS7a4kX3Q28YgqzzK4N0U65zhTrllIxgGfcYDW5KpfIRLbMKvkllgsDKamVpyQ_SRM2PWKg
10.38864278793335
👦 > Hello!
🤖 > HTTPSConnectionPool(host='chat-server.tenant-forefront-default.knative.chi.coreweave.com', port=443): Max retries exceeded with url: /chat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
sua_2Qy0ZA61gipy8hVZlSmRrxnl9JM
{"response":{"object":"sign_up_attempt","id":"sua_2Qy0ZA61gipy8hVZlSmRrxnl9JM","status":"missing_requirements","required_fields":["email_address"],"optional_fields":["oauth_google","phone_number","first_name","last_name","password"],"missing_fields":[],"unverified_fields":["email_address"],"verifications":{"email_address":{"status":"unverified","strategy":"email_link","attempts":null,"expire_at":1686311166591,"next_action":"needs_attempt","supported_strategies":["email_link"]},"phone_number":null,"web3_wallet":null,"external_account":null},"username":null,"email_address":"brainyeland9@internetkeno.com","phone_number":null,"web3_wallet":null,"password_enabled":false,"first_name":null,"last_name":null,"unsafe_metadata":{},"public_metadata":{},"custom_action":false,"external_id":null,"created_session_id":null,"created_user_id":null,"abandon_at":1686396966118},"client":{"object":"client","id":"client_2Qy0ZCgSlN7aBBEbe0TMqWhrKhr","sessions":[],"sign_in":null,"sign_up":{"object":"sign_up_attempt","id":"sua_2Qy0ZA61gipy8hVZlSmRrxnl9JM","status":"missing_requirements","required_fields":["email_address"],"optional_fields":["phone_number","password","first_name","last_name","oauth_google"],"missing_fields":[],"unverified_fields":["email_address"],"verifications":{"email_address":{"status":"unverified","strategy":"email_link","attempts":null,"expire_at":1686311166591,"next_action":"needs_attempt","supported_strategies":["email_link"]},"phone_number":null,"web3_wallet":null,"external_account":null},"username":null,"email_address":"brainyeland9@internetkeno.com","phone_number":null,"web3_wallet":null,"password_enabled":false,"first_name":null,"last_name":null,"unsafe_metadata":{},"public_metadata":{},"custom_action":false,"external_id":null,"created_session_id":null,"created_user_id":null,"abandon_at":1686396966118},"last_active_session_id":null,"created_at":1686310566115,"updated_at":1686310566129}}
64830ea92baa2f54718bc3b4
https://clerk.forefront.ai/v1/verify?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODYzMTExNjYsImlpZCI6Imluc18yTzZ3UTFYd3dxVFdXUWUyQ1VYZHZ2bnNaY2UiLCJydXJsIjoiaHR0cHM6Ly9hY2NvdW50cy5mb3JlZnJvbnQuYWkvc2lnbi11cC92ZXJpZnkiLCJzaWQiOiJzdWFfMlF5MFpBNjFnaXB5OGhWWmxTbVJyeG5sOUpNIiwic3QiOiJzaWduX3VwX2F0dGVtcHQiLCJ2aWQiOiJ2ZXJfMlF5MFpEek5WMnZSWkNqOVd1R3ljOHlZeUpFIn0.fvpa7qrYYlRyIBTfebdNxU3v6Yoma1UBdktGTmrMlHvMHJTBv8V2uDvLm42KniuSByfNkJjTd3QOLVFrDFh5LGIsRvoip3HerjFWTAj5amCZFJQmjse9rMvMeCCRh7hN8AJaXPCQTYzfjR3P5P1HxrEv13ujp_akvImvgeyGVBerJ2Zf4wXe4bImYxTp47z-k1mZZ8WEi6M378lxCrFvp4LxltkbA4bbmfmdn-yt-7IZqD4FNyj-ZlKYJAtMY8ruC0sq_lC_AQ_72tjmoutf90QeU6xvRcIg4zZQ4jwiZfL2Of5hIoSDMdPNs-ltdD6ZVQllEVVM6__PBFLwO5e8sw
10.139719247817993`
As you can see, this is what the gpt4 code prints. After this it just either returns to the input statement or just crashes. And i noticed that Alpaca 7B model in freegpt seems to be dumb, it just repeats the question i asked sometimes (most of the time) could u solve that as well? Thankyou!

**Comment by Shreyas-ITB** [comment]
And sometimes while running gpt4 code i even get this small error:
`Traceback (most recent call last):
  File "C:\Users\Shreyas-ITB\Desktop\jarvis\test.py", line 13, in <module>
    token = gpt4.Account.create(logging=True)
  File "C:\Users\Shreyas-ITB\Desktop\jarvis\virtvenv\lib\site-packages\freeGPT\gpt4\__init__.py", line 59, in create
    mail_client = MailTm().get_account()
  File "C:\Users\Shreyas-ITB\Desktop\jarvis\virtvenv\lib\site-packages\pymailtm\pymailtm.py", line 187, in get_account
    response = self._make_account_request("accounts", address, password)
  File "C:\Users\Shreyas-ITB\Desktop\jarvis\virtvenv\lib\site-packages\pymailtm\pymailtm.py", line 207, in _make_account_request
    raise CouldNotGetAccountException(f"HTTP {r.status_code}")
pymailtm.pymailtm.CouldNotGetAccountException: HTTP 422`

**Comment by Ruu3f** [comment]
No worries, it's not an issue on your end. I'll take care of fixing GPT-4 soon, as it's currently non functional. Unfortunately, I haven't had much time to work on it lately.

About Alpaca_7b, its replies like that only its not a error or a issue.
