### ISSUE TITLE
name 'Session' is not defined

### ISSUE THREAD

**Issue by feusagittaire** [Ruu3f/freeGPT#4]
Hi! I'm facing an error when trying to use gpt3

from freeGPT import gpt3

try:
   # Remove the 'proxy' variable and the 'proxies' parameter if you don't want to use a proxy.
   resp = gpt3.Completion.create(prompt=prompt)
   print(f"🤖 > {str(resp['text'])}")
except Exception as e:
  print(f"🤖 > {str(e)}")

Output:
🤖 > name 'Session' is not defined

**Comment by Ruu3f** [comment]
Simply, `pip install --upgrade freeGPT`

**Comment by feusagittaire** [comment]
My bad, I forgot to reinitialize the environment! But still, it gives me this error🤖 > Unable to fetch the response.

**Comment by Ruu3f** [comment]
Yeah, sometimes it isn't able to fetch data from the website so simply this error comes.
