### ISSUE TITLE
Upon installing the FreeGPT library, I encountered the following error. Could you please assist me in identifying the issue? Thank you.

### ISSUE THREAD

**Issue by charles2268** [Ruu3f/freeGPT#9]
![image](https://github.com/Ruu3f/freeGPT/assets/39716978/488e79b8-d1e0-4087-9c55-b579e8c36943)

**Comment by Mohamed01555** [comment]
please provide your code

**Comment by Ruu3f** [comment]
> ![image](https://user-images.githubusercontent.com/39716978/261785500-488e79b8-d1e0-4087-9c55-b579e8c36943.png)

You need to replace 'MODEL NAME' with a available model. Example: gpt3, gpt4, falcon_40b, etc.

**Comment by charles2268** [comment]
> 
Thank you very much！
